### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DillaDonuts** [nicolasartman/town-of-salem-tool#2]
I find this tool interesting. It would be nice if you could provide some info on how to properly inject it into the game,

**Comment by nicolasartman** [comment]
Sure! I'll ping my friend (since a lot of the functionality is done through color changes that only he remembers the meaning of) and we'll make a quick screencast

**Comment by VelocityRa** [comment]
No answer...

**Comment by nicolasartman** [comment]
Sadly the designer of the interface (my friend) hasn't had time to make a screencast. I'll be sure to update if/when we're able to make one though! At this point I've honestly forgotten what most of the features do :P It's generally for marking voting history so you can track who is suspicious.

**Comment by nicolasartman** [comment]
I added some installation instructions in case they're helpful, though it won't really fix the complete lack of UI docs

**Comment by nicolasartman** [comment]
The chance of my friend recording instructions for this is near zero now, so please consider this deprecated. I'm not even sure if it works with town of Salem any longer.
