### ISSUE TITLE
how can i use it 

### ISSUE THREAD

**Issue by oguzhannonal** [nicolasartman/town-of-salem-tool#4]
can you help me ? please..

**Comment by nicolasartman** [comment]
Hi Sheldon. Unfortunately this project is merely up in case someone wants to use bits of it for another project. I'm not even sure if it works with town of Salem any longer and the friend i built it for has moved on to other games. You can reference the readme to try to set it up yourself but the behaviors are lost to time now so I'm not sure if it'll be of much use.
